# Generated by Django 6.0.1 on 2026-02-23 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customerfield_customertag_customer_anniversary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('auto_assign', models.BooleanField(default=False, help_text='Automatically assign new tickets to available staff', verbose_name='Auto-assign tickets')),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Default Priority')),
                ('sla_first_response_hours', models.PositiveIntegerField(default=24, help_text='Maximum hours for first response to a ticket', verbose_name='SLA First Response (hours)')),
                ('sla_resolution_hours', models.PositiveIntegerField(default=72, help_text='Maximum hours for ticket resolution', verbose_name='SLA Resolution (hours)')),
                ('enable_customer_notifications', models.BooleanField(default=True, help_text='Send email notifications to customers on ticket updates', verbose_name='Enable Customer Notifications')),
                ('close_resolved_after_days', models.PositiveIntegerField(default=7, help_text='Automatically close resolved tickets after this many days', verbose_name='Auto-close Resolved After (days)')),
            ],
            options={
                'verbose_name': 'Support Settings',
                'verbose_name_plural': 'Support Settings',
                'db_table': 'support_supportsettings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('success', 'Green'), ('warning', 'Orange'), ('error', 'Red'), ('neutral', 'Gray')], default='primary', max_length=20, verbose_name='Color')),
                ('icon', models.CharField(choices=[('help-circle-outline', 'General'), ('bug-outline', 'Bug'), ('construct-outline', 'Product Issue'), ('cut-outline', 'Service Issue'), ('card-outline', 'Billing'), ('shield-checkmark-outline', 'Warranty'), ('alert-circle-outline', 'Complaint'), ('bulb-outline', 'Suggestion'), ('chatbox-outline', 'Feedback')], default='help-circle-outline', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Ticket Category',
                'verbose_name_plural': 'Ticket Categories',
                'db_table': 'support_ticketcategory',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('ticket_number', models.CharField(help_text='Auto-generated ticket reference number', max_length=20, verbose_name='Ticket Number')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting on Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('assigned_to', models.UUIDField(blank=True, help_text='UUID of the assigned staff member', null=True, verbose_name='Assigned To')),
                ('assigned_to_name', models.CharField(blank=True, max_length=255, verbose_name='Assigned To Name')),
                ('related_sale', models.UUIDField(blank=True, null=True, verbose_name='Related Sale')),
                ('related_product', models.UUIDField(blank=True, null=True, verbose_name='Related Product')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='First Response At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='customers.customer', verbose_name='Customer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.ticketcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'support_ticket',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('message', models.TextField(verbose_name='Message')),
                ('author_id', models.UUIDField(blank=True, null=True, verbose_name='Author ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='Author Name')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes are only visible to staff', verbose_name='Internal Note')),
                ('attachments', models.JSONField(blank=True, help_text='List of attachment file paths or URLs', null=True, verbose_name='Attachments')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'db_table': 'support_ticketmessage',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['hub_id', 'ticket_number'], name='support_tic_hub_id_154cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['hub_id', 'status'], name='support_tic_hub_id_1ae9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['hub_id', 'priority'], name='support_tic_hub_id_e03b43_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['hub_id', 'assigned_to'], name='support_tic_hub_id_46c250_idx'),
        ),
    ]
